// Profile texts in 10 languages. English is the default (README.md).
// Order of `build` and `principles` items matches BUILD_ICONS / PRINCIPLE_ICONS.

export const BUILD_ICONS = ['handshake', 'factory', 'package', 'cable', 'bot', 'target', 'smartphone', 'messages-square'];
export const PRINCIPLE_ICONS = ['shield-check', 'zap', 'flask-conical', 'languages'];

export const LANGS = [
  {
    code: 'en',
    location: 'Bursa, Türkiye',
    labels: { about: 'About', build: 'What I build', flow: 'How it fits together', stack: 'Tech stack', principles: 'Principles' },
    about: [
      { text: 'I design and build business software end to end, from the database and APIs to the web and mobile screens people use every day. My work sits where sales, production and warehouse operations meet: ' },
      { text: 'CRM, ERP, MES and WMS systems', bold: true },
      { text: ', the integrations that keep them in sync, and ' },
      { text: 'AI-powered tools', bold: true },
      { text: " that take repetitive work off people's plates." },
    ],
    build: [
      ['CRM', 'Customer 360, sales pipeline, quotes and dealer networks, with role-based access and a full audit trail.'],
      ['MES', 'Work orders, shop-floor data capture and real-time production tracking and reporting.'],
      ['WMS', 'Receiving, put-away, picking and shipping, driven by barcode-based mobile workflows.'],
      ['ERP integrations', 'Reliable two-way sync of customers, products, orders and invoices across companies.'],
      ['AI & automation', 'LLM-powered assistants and AI agents that automate sales and back-office workflows.'],
      ['Customer discovery', 'Lead generation pipelines that find potential customers, enrich data and score leads.'],
      ['Mobile apps', 'iOS and Android apps and installable PWAs for sales, field and shop-floor teams.'],
      ['Real-time collaboration', 'Live messaging, notifications and video meetings built into business apps.'],
    ],
    principles: [
      ['Secure by default', 'Authentication, authorization, encryption and audit trails from day one.'],
      ['Fast', 'Screens and actions designed to respond in under a second.'],
      ['Tested', 'Unit, integration and end-to-end tests on every change.'],
      ['Global-ready', 'Multi-language interfaces with accessibility built in.'],
    ],
    flow: {
      front: 'Front office',
      back: 'Back office',
      nodes: { ai: ['AI agents', 'lead discovery'], crm: ['CRM', 'customers · pipeline'], erp: ['ERP', 'finance · stock'], mes: ['MES', 'production tracking'], wms: ['WMS', 'receiving · shipping'] },
      tags: { leads: 'qualified leads', orders: 'orders', work: 'work orders', stock: 'stock levels', goods: 'finished goods' },
      apps: 'Web & mobile apps · PWA, iOS, Android',
    },
  },
  {
    code: 'tr',
    location: 'Bursa, Türkiye',
    labels: { about: 'Hakkımda', build: 'Neler geliştiriyorum', flow: 'Sistemler nasıl birleşiyor', stack: 'Teknolojiler', principles: 'İlkeler' },
    about: [
      { text: "Veritabanı ve API'lerden insanların her gün kullandığı web ve mobil ekranlara kadar iş yazılımlarını uçtan uca tasarlayıp geliştiriyorum. Çalışmalarım satış, üretim ve depo operasyonlarının kesiştiği noktada: " },
      { text: 'CRM, ERP, MES ve WMS sistemleri', bold: true },
      { text: ', bunları senkron tutan entegrasyonlar ve tekrarlayan işleri insanların üzerinden alan ' },
      { text: 'yapay zeka destekli araçlar', bold: true },
      { text: '.' },
    ],
    build: [
      ['CRM', 'Müşteri 360, satış hunisi, teklifler ve bayi ağları; rol bazlı yetki ve eksiksiz denetim kaydıyla.'],
      ['MES', 'İş emirleri, sahadan veri toplama, gerçek zamanlı üretim takibi ve raporlama.'],
      ['WMS', 'Barkodlu mobil akışlarla mal kabul, yerleştirme, toplama ve sevkiyat.'],
      ['ERP entegrasyonları', 'Müşteri, ürün, sipariş ve faturaların şirketler arasında güvenilir, çift yönlü senkronu.'],
      ['Yapay zeka ve otomasyon', 'Satış ve arka ofis iş akışlarını otomatikleştiren LLM tabanlı asistanlar ve yapay zeka ajanları.'],
      ['Müşteri keşfi', 'Potansiyel müşterileri bulan, verilerini zenginleştiren ve adayları puanlayan otomatik akışlar.'],
      ['Mobil uygulamalar', "Satış, saha ve üretim ekipleri için iOS ve Android uygulamaları ile kurulabilir PWA'lar."],
      ['Gerçek zamanlı iş birliği', 'İş uygulamalarına yerleşik canlı mesajlaşma, bildirimler ve görüntülü toplantılar.'],
    ],
    principles: [
      ['Varsayılan olarak güvenli', 'İlk günden kimlik doğrulama, yetkilendirme, şifreleme ve denetim kaydı.'],
      ['Hızlı', 'Ekranlar ve işlemler bir saniyenin altında yanıt verecek şekilde tasarlanır.'],
      ['Test edilmiş', 'Her değişiklikte birim, entegrasyon ve uçtan uca testler.'],
      ['Küresel', 'Erişilebilirliği gözeten çok dilli arayüzler.'],
    ],
    flow: {
      front: 'Ön ofis',
      back: 'Arka ofis',
      nodes: { ai: ['Yapay zeka ajanları', 'aday keşfi'], crm: ['CRM', 'müşteriler · satış'], erp: ['ERP', 'finans · stok'], mes: ['MES', 'üretim takibi'], wms: ['WMS', 'mal kabul · sevkiyat'] },
      tags: { leads: 'nitelikli adaylar', orders: 'siparişler', work: 'iş emirleri', stock: 'stok seviyeleri', goods: 'mamul ürünler' },
      apps: 'Web ve mobil uygulamalar · PWA, iOS, Android',
    },
  },
  {
    code: 'de',
    location: 'Bursa, Türkei',
    labels: { about: 'Über mich', build: 'Was ich entwickle', flow: 'So greift alles ineinander', stack: 'Tech-Stack', principles: 'Prinzipien' },
    about: [
      { text: 'Ich konzipiere und entwickle Unternehmenssoftware durchgängig, von der Datenbank und den APIs bis zu den Web- und Mobile-Oberflächen, mit denen Menschen täglich arbeiten. Meine Arbeit liegt dort, wo Vertrieb, Produktion und Lager zusammenkommen: ' },
      { text: 'CRM-, ERP-, MES- und WMS-Systeme', bold: true },
      { text: ', die Integrationen, die sie synchron halten, und ' },
      { text: 'KI-gestützte Tools', bold: true },
      { text: ', die repetitive Arbeit abnehmen.' },
    ],
    build: [
      ['CRM', 'Kunden-360°, Vertriebspipeline, Angebote und Händlernetze, mit rollenbasiertem Zugriff und lückenlosem Audit-Trail.'],
      ['MES', 'Arbeitsaufträge, Betriebsdatenerfassung sowie Produktionsverfolgung und Reporting in Echtzeit.'],
      ['WMS', 'Wareneingang, Einlagerung, Kommissionierung und Versand mit barcodebasierten mobilen Abläufen.'],
      ['ERP-Integrationen', 'Zuverlässige bidirektionale Synchronisation von Kunden, Artikeln, Aufträgen und Rechnungen über Firmen hinweg.'],
      ['KI & Automatisierung', 'LLM-gestützte Assistenten und KI-Agenten, die Vertriebs- und Backoffice-Abläufe automatisieren.'],
      ['Kundengewinnung', 'Lead-Pipelines, die potenzielle Kunden finden, Daten anreichern und Leads bewerten.'],
      ['Mobile Apps', 'iOS- und Android-Apps sowie installierbare PWAs für Vertrieb, Außendienst und Fertigung.'],
      ['Echtzeit-Zusammenarbeit', 'Chat, Benachrichtigungen und Videomeetings direkt in Geschäftsanwendungen.'],
    ],
    principles: [
      ['Sicher per Design', 'Authentifizierung, Autorisierung, Verschlüsselung und Audit-Trails ab dem ersten Tag.'],
      ['Schnell', 'Oberflächen und Aktionen reagieren in unter einer Sekunde.'],
      ['Getestet', 'Unit-, Integrations- und End-to-End-Tests bei jeder Änderung.'],
      ['Global einsetzbar', 'Mehrsprachige Oberflächen mit eingebauter Barrierefreiheit.'],
    ],
    flow: {
      front: 'Front-Office',
      back: 'Back-Office',
      nodes: { ai: ['KI-Agenten', 'Lead-Suche'], crm: ['CRM', 'Kunden · Pipeline'], erp: ['ERP', 'Finanzen · Bestand'], mes: ['MES', 'Produktionsverfolgung'], wms: ['WMS', 'Eingang · Versand'] },
      tags: { leads: 'qualifizierte Leads', orders: 'Aufträge', work: 'Arbeitsaufträge', stock: 'Lagerbestände', goods: 'Fertigwaren' },
      apps: 'Web- & Mobile-Apps · PWA, iOS, Android',
    },
  },
  {
    code: 'fr',
    location: 'Bursa, Turquie',
    labels: { about: 'À propos', build: 'Ce que je conçois', flow: "Comment tout s'articule", stack: 'Stack technique', principles: 'Principes' },
    about: [
      { text: "Je conçois et développe des logiciels métier de bout en bout, de la base de données et des API jusqu'aux écrans web et mobiles utilisés au quotidien. Mon travail se situe là où se rejoignent ventes, production et logistique : " },
      { text: 'systèmes CRM, ERP, MES et WMS', bold: true },
      { text: ', les intégrations qui les synchronisent, et des ' },
      { text: "outils propulsés par l'IA", bold: true },
      { text: ' qui libèrent les équipes des tâches répétitives.' },
    ],
    build: [
      ['CRM', "Vue client 360°, pipeline commercial, devis et réseaux de revendeurs, avec accès par rôle et piste d'audit complète."],
      ['MES', "Ordres de fabrication, collecte des données d'atelier et suivi de production en temps réel."],
      ['WMS', 'Réception, rangement, préparation et expédition, pilotés par des flux mobiles à codes-barres.'],
      ['Intégrations ERP', 'Synchronisation bidirectionnelle fiable des clients, articles, commandes et factures entre sociétés.'],
      ['IA & automatisation', 'Assistants basés sur des LLM et agents IA qui automatisent les processus commerciaux et administratifs.'],
      ['Prospection clients', 'Pipelines de génération de leads qui trouvent des prospects, enrichissent les données et les qualifient.'],
      ['Applications mobiles', 'Applications iOS et Android et PWA installables pour les équipes commerciales, terrain et atelier.'],
      ['Collaboration en temps réel', 'Messagerie instantanée, notifications et visioconférences intégrées aux applications métier.'],
    ],
    principles: [
      ['Sécurisé par défaut', "Authentification, autorisation, chiffrement et piste d'audit dès le premier jour."],
      ['Rapide', "Écrans et actions conçus pour répondre en moins d'une seconde."],
      ['Testé', "Tests unitaires, d'intégration et de bout en bout à chaque modification."],
      ["Prêt pour l'international", 'Interfaces multilingues avec accessibilité intégrée.'],
    ],
    flow: {
      front: 'Front-office',
      back: 'Back-office',
      nodes: { ai: ['Agents IA', 'prospection'], crm: ['CRM', 'clients · pipeline'], erp: ['ERP', 'finance · stocks'], mes: ['MES', 'suivi de production'], wms: ['WMS', 'réception · expédition'] },
      tags: { leads: 'leads qualifiés', orders: 'commandes', work: 'ordres de fabrication', stock: 'niveaux de stock', goods: 'produits finis' },
      apps: 'Applications web & mobiles · PWA, iOS, Android',
    },
  },
  {
    code: 'es',
    location: 'Bursa, Turquía',
    labels: { about: 'Sobre mí', build: 'Qué construyo', flow: 'Cómo encaja todo', stack: 'Tecnologías', principles: 'Principios' },
    about: [
      { text: 'Diseño y desarrollo software empresarial de principio a fin, desde la base de datos y las API hasta las pantallas web y móviles que las personas usan cada día. Mi trabajo está donde se unen ventas, producción y almacén: ' },
      { text: 'sistemas CRM, ERP, MES y WMS', bold: true },
      { text: ', las integraciones que los mantienen sincronizados y ' },
      { text: 'herramientas impulsadas por IA', bold: true },
      { text: ' que eliminan el trabajo repetitivo.' },
    ],
    build: [
      ['CRM', 'Visión 360° del cliente, embudo de ventas, presupuestos y redes de distribuidores, con acceso por roles y auditoría completa.'],
      ['MES', 'Órdenes de trabajo, captura de datos en planta y seguimiento de la producción en tiempo real.'],
      ['WMS', 'Recepción, ubicación, preparación y expedición, con flujos móviles basados en códigos de barras.'],
      ['Integraciones ERP', 'Sincronización bidireccional fiable de clientes, productos, pedidos y facturas entre empresas.'],
      ['IA y automatización', 'Asistentes basados en LLM y agentes de IA que automatizan procesos de ventas y back office.'],
      ['Captación de clientes', 'Flujos de generación de leads que encuentran clientes potenciales, enriquecen datos y califican leads.'],
      ['Apps móviles', 'Apps para iOS y Android y PWA instalables para equipos comerciales, de campo y de planta.'],
      ['Colaboración en tiempo real', 'Mensajería en vivo, notificaciones y videollamadas integradas en las aplicaciones de negocio.'],
    ],
    principles: [
      ['Seguro por defecto', 'Autenticación, autorización, cifrado y auditoría desde el primer día.'],
      ['Rápido', 'Pantallas y acciones diseñadas para responder en menos de un segundo.'],
      ['Probado', 'Pruebas unitarias, de integración y de extremo a extremo en cada cambio.'],
      ['Listo para el mundo', 'Interfaces multilingües con accesibilidad integrada.'],
    ],
    flow: {
      front: 'Front office',
      back: 'Back office',
      nodes: { ai: ['Agentes de IA', 'búsqueda de leads'], crm: ['CRM', 'clientes · embudo'], erp: ['ERP', 'finanzas · stock'], mes: ['MES', 'seguimiento'], wms: ['WMS', 'recepción · envíos'] },
      tags: { leads: 'leads calificados', orders: 'pedidos', work: 'órdenes de trabajo', stock: 'niveles de stock', goods: 'productos terminados' },
      apps: 'Apps web y móviles · PWA, iOS, Android',
    },
  },
  {
    code: 'it',
    location: 'Bursa, Turchia',
    labels: { about: 'Chi sono', build: 'Cosa realizzo', flow: 'Come si integra tutto', stack: 'Tecnologie', principles: 'Principi' },
    about: [
      { text: 'Progetto e sviluppo software gestionale end-to-end, dal database e dalle API fino alle schermate web e mobile che le persone usano ogni giorno. Il mio lavoro si colloca dove vendite, produzione e magazzino si incontrano: ' },
      { text: 'sistemi CRM, ERP, MES e WMS', bold: true },
      { text: ', le integrazioni che li mantengono sincronizzati e ' },
      { text: "strumenti basati sull'IA", bold: true },
      { text: ' che eliminano il lavoro ripetitivo.' },
    ],
    build: [
      ['CRM', 'Vista cliente a 360°, pipeline di vendita, preventivi e reti di rivenditori, con accessi basati sui ruoli e audit trail completo.'],
      ['MES', 'Ordini di lavoro, raccolta dati in reparto e monitoraggio della produzione in tempo reale.'],
      ['WMS', 'Ricevimento, stoccaggio, prelievo e spedizione, guidati da flussi mobili con codici a barre.'],
      ['Integrazioni ERP', 'Sincronizzazione bidirezionale affidabile di clienti, articoli, ordini e fatture tra aziende.'],
      ['IA e automazione', 'Assistenti basati su LLM e agenti IA che automatizzano i processi di vendita e di back office.'],
      ['Ricerca clienti', 'Pipeline di lead generation che trovano potenziali clienti, arricchiscono i dati e valutano i lead.'],
      ['App mobili', 'App iOS e Android e PWA installabili per team commerciali, sul campo e in produzione.'],
      ['Collaborazione in tempo reale', 'Messaggistica live, notifiche e videoconferenze integrate nelle applicazioni aziendali.'],
    ],
    principles: [
      ['Sicuro per impostazione', 'Autenticazione, autorizzazione, crittografia e audit trail fin dal primo giorno.'],
      ['Veloce', 'Schermate e azioni progettate per rispondere in meno di un secondo.'],
      ['Testato', 'Test unitari, di integrazione ed end-to-end a ogni modifica.'],
      ['Pronto per il mondo', 'Interfacce multilingue con accessibilità integrata.'],
    ],
    flow: {
      front: 'Front office',
      back: 'Back office',
      nodes: { ai: ['Agenti IA', 'ricerca lead'], crm: ['CRM', 'clienti · pipeline'], erp: ['ERP', 'finanza · magazzino'], mes: ['MES', 'produzione'], wms: ['WMS', 'arrivi · spedizioni'] },
      tags: { leads: 'lead qualificati', orders: 'ordini', work: 'ordini di lavoro', stock: 'livelli di scorta', goods: 'prodotti finiti' },
      apps: 'App web e mobili · PWA, iOS, Android',
    },
  },
  {
    code: 'ru',
    location: 'Бурса, Турция',
    labels: { about: 'Обо мне', build: 'Что я создаю', flow: 'Как всё связано', stack: 'Технологии', principles: 'Принципы' },
    about: [
      { text: 'Я проектирую и разрабатываю бизнес-приложения от начала до конца: от базы данных и API до веб- и мобильных экранов, с которыми люди работают каждый день. Моя работа там, где встречаются продажи, производство и склад: ' },
      { text: 'системы CRM, ERP, MES и WMS', bold: true },
      { text: ', интеграции, которые поддерживают их синхронизацию, и ' },
      { text: 'инструменты на основе ИИ', bold: true },
      { text: ', избавляющие людей от рутины.' },
    ],
    build: [
      ['CRM', 'Клиент 360°, воронка продаж, коммерческие предложения и дилерские сети с ролевым доступом и полным аудитом.'],
      ['MES', 'Производственные задания, сбор данных в цеху и отслеживание производства в реальном времени.'],
      ['WMS', 'Приёмка, размещение, комплектация и отгрузка на основе мобильных сценариев со штрихкодами.'],
      ['Интеграции с ERP', 'Надёжная двусторонняя синхронизация клиентов, товаров, заказов и счетов между компаниями.'],
      ['ИИ и автоматизация', 'Ассистенты на базе LLM и ИИ-агенты, автоматизирующие продажи и бэк-офис.'],
      ['Поиск клиентов', 'Лидогенерация: поиск потенциальных клиентов, обогащение данных и скоринг лидов.'],
      ['Мобильные приложения', 'Приложения для iOS и Android и устанавливаемые PWA для продаж, выездных и цеховых команд.'],
      ['Совместная работа', 'Чат, уведомления и видеовстречи в реальном времени прямо в бизнес-приложениях.'],
    ],
    principles: [
      ['Безопасность по умолчанию', 'Аутентификация, авторизация, шифрование и аудит с первого дня.'],
      ['Скорость', 'Экраны и действия отвечают быстрее чем за секунду.'],
      ['Тестирование', 'Модульные, интеграционные и сквозные тесты при каждом изменении.'],
      ['Готовность к миру', 'Многоязычные интерфейсы с учётом доступности.'],
    ],
    flow: {
      front: 'Фронт-офис',
      back: 'Бэк-офис',
      nodes: { ai: ['ИИ-агенты', 'поиск лидов'], crm: ['CRM', 'клиенты · воронка'], erp: ['ERP', 'финансы · склад'], mes: ['MES', 'учёт производства'], wms: ['WMS', 'приёмка · отгрузка'] },
      tags: { leads: 'целевые лиды', orders: 'заказы', work: 'задания', stock: 'остатки', goods: 'готовая продукция' },
      apps: 'Веб- и мобильные приложения · PWA, iOS, Android',
    },
  },
  {
    code: 'ar',
    rtl: true,
    location: 'بورصة، تركيا',
    labels: { about: 'نبذة عني', build: 'ماذا أبني', flow: 'كيف تتكامل الأنظمة', stack: 'التقنيات', principles: 'المبادئ' },
    about: [
      { text: 'أصمّم وأطوّر برمجيات الأعمال من البداية إلى النهاية، من قاعدة البيانات وواجهات API إلى شاشات الويب والجوال التي يستخدمها الناس يوميًا. يقع عملي حيث تلتقي المبيعات والإنتاج والمستودعات: ' },
      { text: 'أنظمة CRM و ERP و MES و WMS', bold: true },
      { text: '، والتكاملات التي تبقيها متزامنة، و' },
      { text: 'أدوات مدعومة بالذكاء الاصطناعي', bold: true },
      { text: ' تُعفي الفرق من الأعمال المتكررة.' },
    ],
    build: [
      ['CRM', 'رؤية شاملة للعميل ومسار المبيعات وعروض الأسعار وشبكات الوكلاء، مع صلاحيات حسب الأدوار وسجل تدقيق كامل.'],
      ['MES', 'أوامر العمل وجمع بيانات أرض المصنع وتتبع الإنتاج وتقاريره لحظيًا.'],
      ['WMS', 'الاستلام والتخزين والانتقاء والشحن عبر مسارات عمل جوّالة تعتمد على الباركود.'],
      ['تكاملات ERP', 'مزامنة موثوقة ثنائية الاتجاه للعملاء والمنتجات والطلبات والفواتير بين الشركات.'],
      ['الذكاء الاصطناعي والأتمتة', 'مساعدون قائمون على LLM ووكلاء ذكاء اصطناعي يؤتمتون سير عمل المبيعات والمكاتب الخلفية.'],
      ['اكتشاف العملاء', 'مسارات لتوليد العملاء المحتملين تعثر عليهم وتُثري بياناتهم وتقيّمهم.'],
      ['تطبيقات الجوال', 'تطبيقات iOS و Android وتطبيقات PWA قابلة للتثبيت لفرق المبيعات والميدان والمصنع.'],
      ['التعاون الفوري', 'مراسلة فورية وإشعارات واجتماعات فيديو مدمجة في تطبيقات الأعمال.'],
    ],
    principles: [
      ['آمن افتراضيًا', 'المصادقة والتفويض والتشفير وسجلات التدقيق منذ اليوم الأول.'],
      ['سريع', 'شاشات وإجراءات مصممة للاستجابة في أقل من ثانية.'],
      ['مُختبَر', 'اختبارات الوحدة والتكامل والاختبارات الشاملة مع كل تغيير.'],
      ['جاهز عالميًا', 'واجهات متعددة اللغات مع مراعاة إمكانية الوصول.'],
    ],
    flow: {
      front: 'المكتب الأمامي',
      back: 'المكتب الخلفي',
      nodes: { ai: ['وكلاء الذكاء الاصطناعي', 'اكتشاف العملاء'], crm: ['CRM', 'العملاء · المبيعات'], erp: ['ERP', 'المالية · المخزون'], mes: ['MES', 'تتبع الإنتاج'], wms: ['WMS', 'الاستلام · الشحن'] },
      tags: { leads: 'عملاء مؤهلون', orders: 'الطلبات', work: 'أوامر العمل', stock: 'مستويات المخزون', goods: 'منتجات تامة' },
      apps: 'تطبيقات الويب والجوال · PWA و iOS و Android',
    },
  },
  {
    code: 'zh',
    location: '土耳其 · 布尔萨',
    labels: { about: '关于我', build: '我的工作', flow: '系统如何协同', stack: '技术栈', principles: '原则' },
    about: [
      { text: '我端到端地设计和开发企业软件，从数据库和 API 到人们每天使用的 Web 与移动端界面。我的工作聚焦于销售、生产与仓储的交汇处：' },
      { text: 'CRM、ERP、MES 和 WMS 系统', bold: true },
      { text: '、保持它们同步的集成，以及把人们从重复劳动中解放出来的' },
      { text: 'AI 驱动工具', bold: true },
      { text: '。' },
    ],
    build: [
      ['CRM', '客户 360 视图、销售管道、报价与经销商网络，支持基于角色的访问控制和完整审计追踪。'],
      ['MES', '工单、车间数据采集以及实时生产跟踪与报表。'],
      ['WMS', '收货、上架、拣货与发货，基于条码的移动作业流程。'],
      ['ERP 集成', '客户、产品、订单与发票在各公司之间可靠的双向同步。'],
      ['AI 与自动化', '基于大语言模型的助手和 AI 智能体，自动化销售与后台流程。'],
      ['客户发现', '潜在客户挖掘流程：寻找潜在客户、丰富数据并为线索评分。'],
      ['移动应用', '面向销售、外勤和车间团队的 iOS、Android 应用及可安装的 PWA。'],
      ['实时协作', '内置于业务应用中的即时消息、通知和视频会议。'],
    ],
    principles: [
      ['默认安全', '从第一天起就具备身份验证、授权、加密和审计追踪。'],
      ['快速', '界面与操作的响应时间控制在一秒以内。'],
      ['经过测试', '每次变更都运行单元测试、集成测试和端到端测试。'],
      ['面向全球', '多语言界面，内置无障碍支持。'],
    ],
    flow: {
      front: '前台业务',
      back: '后台业务',
      nodes: { ai: ['AI 智能体', '潜客发现'], crm: ['CRM', '客户 · 销售管道'], erp: ['ERP', '财务 · 库存'], mes: ['MES', '生产跟踪'], wms: ['WMS', '收货 · 发货'] },
      tags: { leads: '合格线索', orders: '订单', work: '工单', stock: '库存水平', goods: '成品' },
      apps: 'Web 与移动应用 · PWA、iOS、Android',
    },
  },
  {
    code: 'ja',
    location: 'トルコ・ブルサ',
    labels: { about: '自己紹介', build: '開発分野', flow: 'システムのつながり', stack: '技術スタック', principles: '大切にしていること' },
    about: [
      { text: 'データベースや API から、日々使われる Web・モバイル画面まで、業務システムを一貫して設計・開発しています。営業・生産・倉庫の業務が交わる領域が専門で、' },
      { text: 'CRM・ERP・MES・WMS システム', bold: true },
      { text: '、それらを同期させる連携、そして繰り返し作業を減らす' },
      { text: 'AI 活用ツール', bold: true },
      { text: 'を手がけています。' },
    ],
    build: [
      ['CRM', '顧客 360 度ビュー、営業パイプライン、見積、販売代理店ネットワーク。ロールベースのアクセス制御と完全な監査ログ付き。'],
      ['MES', '作業指示、現場データ収集、リアルタイムの生産管理とレポート。'],
      ['WMS', '入荷・格納・ピッキング・出荷を、バーコードを使ったモバイル業務で。'],
      ['ERP 連携', '顧客・製品・受注・請求書を会社間で確実に双方向同期。'],
      ['AI と自動化', '営業とバックオフィス業務を自動化する LLM アシスタントと AI エージェント。'],
      ['顧客開拓', '見込み顧客を発見し、データを補完し、リードをスコアリングするパイプライン。'],
      ['モバイルアプリ', '営業・フィールド・現場チーム向けの iOS／Android アプリとインストール可能な PWA。'],
      ['リアルタイム連携', '業務アプリに組み込まれたチャット、通知、ビデオ会議。'],
    ],
    principles: [
      ['セキュアが標準', '初日から認証・認可・暗号化・監査ログを備えます。'],
      ['高速', '画面と操作は 1 秒以内の応答を目指して設計。'],
      ['テスト済み', '変更のたびにユニット・結合・E2E テストを実行。'],
      ['グローバル対応', 'アクセシビリティに配慮した多言語インターフェース。'],
    ],
    flow: {
      front: 'フロントオフィス',
      back: 'バックオフィス',
      nodes: { ai: ['AI エージェント', 'リード発掘'], crm: ['CRM', '顧客 · パイプライン'], erp: ['ERP', '財務 · 在庫'], mes: ['MES', '生産管理'], wms: ['WMS', '入荷 · 出荷'] },
      tags: { leads: '有望リード', orders: '受注', work: '作業指示', stock: '在庫水準', goods: '完成品' },
      apps: 'Web・モバイルアプリ · PWA、iOS、Android',
    },
  },
];
